services:
  db:
    build: ./database
    container_name: db
    environment:
      POSTGRES_DB: llmmap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "25432:5432"

  ollama:
    build: ./ollama
    container_name: ollama_llama3
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  backend:
    build: ./backend
    container_name: backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: llmmap
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
      - ollama

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "9002:9002" # Ensure this matches the port in webpack.config.js
    depends_on:
      - backend

volumes:
  ollama-data:
  db-data:
