services:
  db:
    build: ./database
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "$DB_EXTERNAL_PORT:5432"

  ollama:
    build: ./ollama
    container_name: ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_HOST=0.0.0.0:11434
      - LLM_MODEL=$LLM_MODEL
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    ports:
      - "$LLM_EXTERNAL_PORT:11434"
    volumes:
      - ollama-data:/root/.ollama

  backend:
    build: ./backend
    container_name: backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      LLM_MODEL: $LLM_MODEL
      FRONTEND_URL: $FRONTEND_URL
      FRONTEND_EXTERNAL_PORT: $FRONTEND_EXTERNAL_PORT
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
    volumes:
      - ./backend:/app
    ports:
      - "$BACKEND_EXTERNAL_PORT:8001"
    depends_on:
      - db
      - ollama

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "$FRONTEND_EXTERNAL_PORT:9001"
    environment:
      BACKEND_URL: $BACKEND_URL
      BACKEND_EXTERNAL_PORT: $BACKEND_EXTERNAL_PORT
      MAPTILER_API_KEY: $MAPTILER_API_KEY
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  ollama-data:
  db-data:
